/* tslint:disable */
/* eslint-disable */
/**
 * management
 * 企業向け画面のAPIについて説明します。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */